from environs import Env

env = Env()
env.read_env()

class Settings():
    EVERNOTE_CONSUMER_KEY = env.str('EVERNOTE_CONSUMER_KEY')
    EVERNOTE_CONSUMER_SECRET = env.str('EVERNOTE_CONSUMER_SECRET')
    EVERNOTE_PERSONAL_TOKEN = env.str('EVERNOTE_PERSONAL_TOKEN')

    JOURNAL_TEMPLATE_NOTE_GUID = env.str('JOURNAL_TEMPLATE_NOTE_GUID')
    JOURNAL_NOTEBOOK_GUID = env.str('JOURNAL_NOTEBOOK_GUID')

    INBOX_NOTEBOOK_GUID = env.str('INBOX_NOTEBOOK_GUID')

